#!/bin/bash

# 🚀 TriAgent v2 - Railway Deployment Guide

echo "═══════════════════════════════════════════════════════════"
echo "🚀 RAILWAY DEPLOYMENT - Quick Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Step 1: Verify everything is committed
echo "✅ Step 1: Prepare for deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  # Make sure all code is committed:"
echo "  git add ."
echo "  git commit -m 'Production ready - TriAgent v2'"
echo "  git push origin main"
echo ""
echo "✅ Then proceed to Railway deployment"
echo ""

# Step 2: Railway deployment
echo "📦 Step 2: Deploy to Railway"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub (or create account)"
echo "3. Click: 'New Project'"
echo "4. Select: 'Deploy from GitHub repo'"
echo "5. Find and select: 'triagent-v2' repository"
echo "6. Railway will auto-detect environment (Node.js)"
echo "7. Click: 'Deploy'"
echo ""
echo "⏳ Wait for deployment to complete (2-5 minutes)"
echo ""

# Step 3: Configure environment variables
echo "🔧 Step 3: Add Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Railway Dashboard:"
echo ""
echo "1. Go to your deployed project"
echo "2. Click: 'Variables' (in left menu)"
echo "3. Add these variables from your server/.env:"
echo ""
echo "   ANTHROPIC_API_KEY=sk-ant-..."
echo "   SILICONFLOW_API_KEY=sk-..."
echo "   GEMINI_API_KEY=AIza..."
echo "   GROQ_API_KEY=gsk-..."
echo "   FIREWORKS_API_KEY=..."
echo "   COHERE_API_KEY=..."
echo ""
echo "4. Click: 'Save'"
echo "5. Railway auto-redeploys with new env vars"
echo ""

# Step 4: Get your public URL
echo "🌐 Step 4: Get Your Public URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After deployment completes:"
echo "1. Go to Railway project dashboard"
echo "2. Look for 'Domains' section"
echo "3. You'll see: https://your-triagent-api-xyz.railway.app"
echo ""
echo "✅ This is your production API URL!"
echo ""

# Step 5: Test the deployment
echo "✅ Step 5: Test Your Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test your API is working:"
echo ""
echo "  curl https://your-triagent-api-xyz.railway.app/health"
echo ""
echo "Expected response: {\"status\":\"ok\",\"timestamp\":...}"
echo ""

# Step 6: Connect dashboard (optional)
echo "📊 Step 6: Optional - Deploy Dashboard to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To add a frontend dashboard:"
echo "1. Go to: https://vercel.com/new"
echo "2. Import same repository"
echo "3. Set environment variable:"
echo "   NEXT_PUBLIC_API_URL=https://your-railway-url.railway.app"
echo "4. Deploy"
echo ""
echo "Dashboard will be live at: https://triagent-v2.vercel.app"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🎉 DEPLOYMENT COMPLETE!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Your system is now:"
echo "  ✅ Running on Railway (production)"
echo "  ✅ Auto-scaled"
echo "  ✅ HTTPS/SSL enabled"
echo "  ✅ 24/7 uptime"
echo "  ✅ Public API URL"
echo ""
echo "API URL: https://your-triagent-api-xyz.railway.app"
echo ""
echo "Docs: See RAILWAY_DEPLOYMENT.md for more details"
echo ""
